package dev.dancherbu.ccm.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;

public record IndexCoverageSnapshot(
        @JsonProperty(required = true, value = "generatedAt") String generatedAt,
        @JsonProperty(required = true, value = "reindexRunId") String reindexRunId,
        @JsonProperty(required = true, value = "reindexProjectName") String reindexProjectName,
        @JsonProperty(required = true, value = "reindexQueuePosition") int reindexQueuePosition,
        @JsonProperty(required = true, value = "reindexQueueTotal") int reindexQueueTotal,
        @JsonProperty(required = true, value = "reindexInProgress") boolean reindexInProgress,
        @JsonProperty(required = true, value = "reindexIndexedFiles") int reindexIndexedFiles,
        @JsonProperty(required = true, value = "reindexFailedFiles") int reindexFailedFiles,
        @JsonProperty(required = true, value = "reindexStartedAt") String reindexStartedAt,
        @JsonProperty(required = true, value = "reindexUpdatedAt") String reindexUpdatedAt,
        @JsonProperty(required = true, value = "reindexLastIndexedPath") String reindexLastIndexedPath,
        @JsonProperty(required = true, value = "reindexLastErrorPath") String reindexLastErrorPath,
        @JsonProperty(required = true, value = "watchRoot") String watchRoot,
        @JsonProperty(required = true, value = "embeddingModel") String embeddingModel,
        @JsonProperty(required = true, value = "embeddingCoverageThresholdPercent") double embeddingCoverageThresholdPercent,
        @JsonProperty(required = true, value = "embeddingCoverageThresholdMet") boolean embeddingCoverageThresholdMet,
        @JsonProperty(required = true, value = "embeddingCoverageShortfallPercent") double embeddingCoverageShortfallPercent,
        @JsonProperty(required = true, value = "fileCoverageThresholdPercent") double fileCoverageThresholdPercent,
        @JsonProperty(required = true, value = "fileCoverageThresholdMet") boolean fileCoverageThresholdMet,
        @JsonProperty(required = true, value = "fileCoverageThresholdShortfallPercent") double fileCoverageThresholdShortfallPercent,
        @JsonProperty(required = true, value = "chunkCoverageThresholdPercent") double chunkCoverageThresholdPercent,
        @JsonProperty(required = true, value = "chunkCoverageThresholdMet") boolean chunkCoverageThresholdMet,
        @JsonProperty(required = true, value = "chunkCoverageThresholdShortfallPercent") double chunkCoverageThresholdShortfallPercent,
        @JsonProperty(required = true, value = "semanticCoverageThresholdPercent") double semanticCoverageThresholdPercent,
        @JsonProperty(required = true, value = "semanticCoverageThresholdMet") boolean semanticCoverageThresholdMet,
        @JsonProperty(required = true, value = "semanticCoverageThresholdShortfallPercent") double semanticCoverageThresholdShortfallPercent,
        @JsonProperty(required = true, value = "warnings") List<String> warnings,
        @JsonProperty(required = true, value = "totalProjects") int totalProjects,
        @JsonProperty(required = true, value = "totalIndexableFiles") int totalIndexableFiles,
        @JsonProperty(required = true, value = "embeddedFiles") int embeddedFiles,
        @JsonProperty(required = true, value = "fileCoveragePercent") double fileCoveragePercent,
        @JsonProperty(required = true, value = "indexedDocuments") int indexedDocuments,
        @JsonProperty(required = true, value = "totalChunks") int totalChunks,
        @JsonProperty(required = true, value = "embeddedChunks") int embeddedChunks,
        @JsonProperty(required = true, value = "chunkCoveragePercent") double chunkCoveragePercent,
        @JsonProperty(required = true, value = "totalSemanticNodes") int totalSemanticNodes,
        @JsonProperty(required = true, value = "embeddedSemanticNodes") int embeddedSemanticNodes,
        @JsonProperty(required = true, value = "semanticCoveragePercent") double semanticCoveragePercent,
        @JsonProperty(required = true, value = "projects") List<IndexCoverageProject> projects) {
}